version: '3'
services:
  redis-proxy:
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    restart: unless-stopped
    environment: # Pass environment variables to the service
      REDIS_URL: redis:6379 
    depends_on: 
      - redis
    ports:
      - "8081:8081"
    networks:
      - backend

  redis:
    image: 'bitnami/redis:5.0'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    restart: unless-stopped
    networks:
      - backend
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
networks:
  backend:   
volumes:
  redis_data:
    driver: local